### ISSUE TITLE
Docker compose does not work on mac m1

### ISSUE THREAD

**Issue by Barsun** [jonfairbanks/local-rag#66]
**Describe the Bug**
when I run docker compose on M1 I get an error `Package installation failed...`

**Troubleshooting**
I have read the Local RAG [troubleshooting guide](../../docs/troubleshooting.md), reviewed my application state and log file:
- [x] Yes
- [ ] No

**How To Reproduce**
1. Run `docker compose up -d `
2. Error while building 

**Expected Behavior**
Application to run

**Screenshots**
<img width="904" alt="image" src="https://github.com/user-attachments/assets/9b09114b-933d-4a10-b7b2-826825f261c9">

**Logs**
If applicable, attach log files to help explain your problem. **Reproducing your issue and sharing a copy of your `local-rag.log` can greatly aid in troubleshooting.**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1

**Comment by unfixa1** [comment]
Some Docker images may not support the ARM architecture (M1). It is recommended to check whether the image you are using has an ARM version, or try to use the --platform linux/amd64 flag to force the use of the x86 architecture.
Or use [servbay](https://servbay.com) instead of docker. servbay runs better than docker on mac and has fewer bugs.

**Comment by Barsun** [comment]
I removed [Pipfile.lock](https://github.com/jonfairbanks/local-rag/blob/develop/Pipfile.lock) from repo and Docker file and it worked 👍

**Comment by Barsun** [comment]
I removed [Pipfile.lock](https://github.com/jonfairbanks/local-rag/blob/develop/Pipfile.lock) from repo and Docker file and it worked 👍
